name: pro_image_editor_tony
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 2.4.4
homepage: https://github.com/tonilsonmanoel/pro_editor_image_tony/
repository: https://github.com/tonilsonmanoel/pro_editor_image_tony/
issue_tracker: https://github.com/tonilsonmanoel/pro_editor_image_tony/
documentation: https://github.com/tonilsonmanoel/pro_editor_image_tony/


topics:
  - image-editor
  - image
  - editor
  - widget
  - painting

screenshots:
  - description: "Showcase from the Image Editor"
    path: assets/showcase.png

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  image_editor: ^1.3.0
  extended_image: ^8.2.0
  rounded_background_text: ^0.5.0
  colorfilter_generator: ^0.0.8
  screenshot: ^2.1.0
  vibration: ^1.8.4
  http: ^1.2.0
  emoji_picker_flutter: ^2.0.0
  image: ^4.1.7
  google_fonts: ^5.1.0
  flutter_font_picker: ^1.4.0
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  network_image_mock: ^2.0.0
  build_runner: ^2.4.8

flutter:
